# Generated by Django 2.2.7 on 2019-11-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('campaign_name', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('char_class', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0)),
                ('race', models.CharField(max_length=100)),
                ('strength', models.PositiveIntegerField()),
                ('dexterity', models.PositiveIntegerField()),
                ('constitution', models.PositiveIntegerField()),
                ('intelligence', models.PositiveIntegerField()),
                ('wisdom', models.PositiveIntegerField()),
                ('charisma', models.PositiveIntegerField()),
                ('armor_class', models.CharField(max_length=100)),
                ('hit_points', models.PositiveIntegerField()),
                ('proficiency_bonus', models.PositiveIntegerField()),
                ('alignment', models.CharField(max_length=100)),
                ('campaign', models.CharField(default=None, max_length=100)),
                ('image', models.TextField()),
                ('slug', models.SlugField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
