# Generated by Django 2.2.7 on 2019-11-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_character_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='bio',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(default='folk hero', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throws',
            field=models.TextField(default='dexterity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skill_proficiencies',
            field=models.TextField(default='animal handling'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(),
        ),
    ]
