# Generated by Django 2.2.7 on 2019-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_character_app', '0002_auto_20191108_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.TextField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthesocietypages.org%2Fsocimages%2Ffiles%2F2009%2F05%2Fnopic_192.gif&f=1&nofb=1'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='saving_throws',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_proficiencies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
