# Generated by Django 2.2.7 on 2019-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_character_app', '0003_auto_20191110_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armor_class',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='charisma',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hit_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiency_bonus',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
