# Generated by Django 2.2.7 on 2019-11-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_character_app', '0004_auto_20191110_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='campaign',
        ),
    ]
